### ISSUE TITLE
Regex destroying URL's?

### ISSUE THREAD

**Issue by Renader** [coryrylan/ngx-json-ld#4]
What exactly is the purpose of the regex that runs over the JSON value?

As far as I can tell, URLs in the schemas are destroyed because of this.

```
export class AppComponent {
  schema = {
    '@context': 'http://schema.org',
    '@type': 'WebSite',
    'name': 'angular.io',
    'url': 'https://angular.io'
  };
}
```

```
<ngx-json-ld [json]="schema"></ngx-json-ld>
```

**Results in:**
![image](https://user-images.githubusercontent.com/16294855/34524416-bfd880e4-f09b-11e7-9471-3d436ac3d5f8.png)

**Works better if I remove the regex:**
![image](https://user-images.githubusercontent.com/16294855/34524454-de055808-f09b-11e7-8c64-efdba94412e6.png)

______________________________________________________

```

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
    
Angular CLI: 1.6.0-rc.2
Node: 7.5.0
OS: linux x64
Angular: 5.1.0-rc.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

@angular/cdk: 5.0.0-rc.2
@angular/cli: 1.6.0-rc.2
@angular/material: 5.0.0-rc.2
@angular-devkit/build-optimizer: 0.0.34
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.39
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.0-rc.2
@schematics/angular: 0.1.9
typescript: 2.4.2
webpack: 3.10.0

```

**Comment by kevinbuhmann** [comment]
It escapes a `</script>` tag in the schema value. We need to fix it for URLs.

**Comment by coryrylan** [comment]
This is for a xss issue described here. https://stackoverflow.com/questions/28643272/how-to-include-an-escapedscript-script-tag-in-a-javascript-variable We will get a fix in soon.

**Comment by kevinbuhmann** [comment]
This should be fixed when @coryrylan published the next release.

**Comment by coryrylan** [comment]
@Renader  try the latest version 0.1.10

**Comment by Renader** [comment]
Thanks for the fast reply - I can confirm it works now correctly!
